apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd-diego-test-recreate
  name: httpd-diego-test-recreate
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd-diego-test
  template:
    metadata:
      labels:
        app: httpd-diego-test
    spec:
      containers:
        - image: httpd:alpine
          name: httpd
          # command: ["/bin/bash", "-c"] # override the default command
          # args: ["sleep 5; exit 1"] # sleep for 5 seconds then exit with an error
  strategy:
    type: RollingUpdate # It will kill all old pods and then create the new ones
